---
default_language_version:
  python: python3.8
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: e1668fe86af3810fbca72b8653fe478e66a0afdc  # frozen: v3.2.0
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md,markdown']
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: pretty-format-json
    args:
    - '--indent'
    - '4'
    - '--autofix'
    - '--no-sort-keys'
  - id: check-toml
  - id: fix-encoding-pragma
    args:
    - '--remove'
- repo: https://github.com/psf/black
  rev: e66be67b9b6811913470f70c28b4d50f94d05b22  # frozen: 20.8b1
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 491b3461d572249de71a7b2572af281322d4f40b  # frozen: 5.6.3
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: eae6397e4c259ed3d057511f6dd5330b92867e62  # frozen: v1.6.0
  hooks:
  - id: python-no-eval
  - id: python-no-log-warn
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint -s no
    language: system
    types: [python]
  - id: mypy
    name: mypy
    entry: mypy --strict --no-strict-optional
    language: system
    types: [python]
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: a27ba454fd1cfd7ce20b60f5a1aee310fd66df82  # frozen: 0.1.0
  hooks:
  - id: yamlfmt
    args:
    - '--mapping'
    - '2'
    - '--sequence'
    - '2'
    - '--offset'
    - '0'
    - '--width'
    - '120'
    - '-p'
