ci:
  skip:
  - pylint
  - mypy
default_language_version:
  python: python3.8
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md,markdown']
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: pretty-format-json
    args:
    - '--indent'
    - '4'
    - '--autofix'
    - '--no-sort-keys'
  - id: check-toml
  - id: fix-encoding-pragma
    args:
    - '--remove'
- repo: https://github.com/psf/black
  rev: 93c10bf9ebccf8d7cc686b0b9579f2e5e41c5328  # frozen: 21.6b0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 1d7e37c3ff2536abf4359f73c46c418cfec12ada  # frozen: 5.9.1
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce  # frozen: v1.9.0
  hooks:
  - id: python-no-eval
  - id: python-no-log-warn
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint -s no
    language: system
    types: [python]
  - id: mypy
    name: mypy
    entry: mypy
    language: system
    types: [python]
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: a27ba454fd1cfd7ce20b60f5a1aee310fd66df82  # frozen: 0.1.0
  hooks:
  - id: yamlfmt
    args:
    - '--mapping'
    - '2'
    - '--sequence'
    - '2'
    - '--offset'
    - '0'
    - '--width'
    - '120'
    - '-p'
    - '--implicit_start'
