name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-ver:
        - "3.8"
    env:
      PYTHON: ${{ matrix.python-ver }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-ver }}
      uses: actions/setup-python@v2.2.1
      with:
        python-version: ${{ matrix.python-ver }}
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-ver }}-pip-${{ hashFiles('**/Pipfile*') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-ver }}-pip-${{ hashFiles('**/Pipfile*') }}
          ${{ runner.os }}-${{ matrix.python-ver }}-pip-
    - name: Install dependencies
      run: |
        pip install -U pipenv
        pipenv install --deploy --dev
    - name: Run tests
      run: pipenv run test
    - uses: codecov/codecov-action@v1.0.13
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: build
        env_vars: PYTHON
        fail_ci_if_error: true
